name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable
      - uses: actions/upload-artifact@v3
        with:
          name: TradingApp-APK
          path: bin/*.apk
          
